### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by PranavSarda** [CybercellVIIT/vishwaCTFWebsite21#23]
Wrong Favicon on Homepage. No favicon on other pages.

**Comment by adityabakare** [comment]
Seems fine on Safari 14.x. Waiting for a confirmation for other browsers.

**Comment by PranavSarda** [comment]
Favicon is still of the old Cyber Logo. Please update with the new logo. Refer About CyberCell Page for new logo.

**Comment by PranavSarda** [comment]
Updated by someone?
