### ISSUE TITLE
Huge Issue : Very big Problem. Urgent Help Needed!

### ISSUE THREAD

**Issue by PranavSarda** [CybercellVIIT/vishwaCTFWebsite21#28]
I cant find the thing I was searching for, help me out guys.

**Comment by kundankabra** [comment]
have you tried google.com ?

**Comment by PranavSarda** [comment]
Never heard of it, woogle.com u said?

**Comment by adityabakare** [comment]
> have you tried google.com

I personally think Bing is the best search engine.

**Comment by Shreeraj-Shivale** [comment]
> 
> 
> have you tried google.com

utterly idiotic!
That stuff doesn't offer any anonymity whatsoever!
Use duck duck go

**Comment by vipul-rajput** [comment]
utterly idiotic!
That stuff doesn't offer any anonymity whatsoever!
Use duck duck go

**Comment by Shreeraj-Shivale** [comment]
> 
> 
> > have you tried google.com
> 
> I personally think Bing is the best search engine.

bruh! MSN is the best...but the real homies use yandex

**Comment by adityabakare** [comment]
> > have you tried google.com
> 
> utterly idiotic!
> That stuff doesn't offer any anonymity whatsoever!
> Use duck duck go

I heard we can hack NASA with it

**Comment by Shreeraj-Shivale** [comment]
> 
> 
> > > have you tried google.com
> > 
> > 
> > utterly idiotic!
> > That stuff doesn't offer any anonymity whatsoever!
> > Use duck duck go
> 
> I heard we can hack NASA with it

amateur 
i hacked nasa with whatsapp

**Comment by adityabakare** [comment]
> > > > have you tried google.com
> > > 
> > > 
> > > utterly idiotic!
> > > That stuff doesn't offer any anonymity whatsoever!
> > > Use duck duck go
> > 
> > 
> > I heard we can hack NASA with it
> 
> amateur
> i hacked nasa with whatsapp

Bhaiyya! Kese kiya bhaiyya!!?? Mujhe bhi sikhao na!! 
![50zv36](https://user-images.githubusercontent.com/39880713/110501583-55010980-8120-11eb-9782-1b3361fb5cef.jpg)

**Comment by Shreeraj-Shivale** [comment]
> 
> 
> > > > > have you tried google.com
> > > > 
> > > > 
> > > > utterly idiotic!
> > > > That stuff doesn't offer any anonymity whatsoever!
> > > > Use duck duck go
> > > 
> > > 
> > > I heard we can hack NASA with it
> > 
> > 
> > amateur
> > i hacked nasa with whatsapp
> 
> Bhaiyya! Kese kiya bhaiyya!!?? Mujhe bhi sikhao na!!
> ![50zv36](https://user-images.githubusercontent.com/39880713/110501583-55010980-8120-11eb-9782-1b3361fb5cef.jpg)
This is how i did it bro

**Comment by PranavSarda** [comment]
Thanks a lot bro! Found it here! :D
